# Site settings
email: documentation@epages.com
url: "https://developer.epages.com"
baseurl: ""
github_url: "https://github.com/ePages-de/epages-docs"
google_analytics:
  default:
    id: UA-71308214-1
  blog:
    id: UA-71308214-2

permalink: /blog/:year/:month/:day/:title.html
paginate: 5
paginate_path: "/blog/page-:num/"
raml:
  - key_prefix: "apps-api-"
    url_prefix: "apps/api-reference/"
    root_file: _raml/apps/api.raml

# Build settings
markdown: kramdown
exclude:
  - circle.yml
  - docker-compose.yml
  - Dockerfile.ngnix
  - Dockerfile.ruby
  - Gemfile
  - Gemfile.lock
  - LICENSE-CC-BY-40.txt
  - LICENSE-MIT.txt
  - Rakefile
  - README.md
  - vendor
include:
  - videos

# Search index settings
search:
  host: localhost:9200
  index:
    name: epages-docs
    settings:
      mappings:
        page:
          properties:
            url:
              type: string
              analyzer: keyword
            title:
              type: string
              analyzer: english
            content:
              type: string
              analyzer: english
        section:
          properties:
            url:
              type: string
              analyzer: keyword
            title:
              type: string
              analyzer: english
            content:
              type: string
              analyzer: english
