# Site settings
title: My Company Documentation
email: apidocs@mycompany.com
description: >
  Welcome to the Developer Program. You'll find comprehensive guides
  and documentation to help you start working with Developer Program
  as quickly as possible, as well as support if you get stuck. Let's
  jump right in!
baseurl: "/jekyll-apidocs"
url: "https://choffmeister.github.io"
raml_root: "_raml/example/simple.raml"

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md

# Deployment settings
deployment:
  type: git
  repo: git@github.com:choffmeister/jekyll-apidocs.git
  branch: gh-pages
