# Site settings
title: ePages Documentation
email: documentation@epages.com
description: >
  This is the primary source of trust for ePages beloved third
  party developers.
url: "https://developer.epages.com"
baseurl: ""
github_url: "https://github.com/ePages-de/epages-docs"
google_analytics:
  default:
    id: UA-37161369-23
  blog:
    id: UA-37161369-24

permalink: /blog/:year/:month/:day/:title.html
raml:
  - key_prefix: "apps-api-"
    url_prefix: "apps/api-reference/"
    root_file: _raml/apps/api.raml

# Build settings
markdown: kramdown
exclude:
  - circle.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - Rakefile
  - README.md
  - Vagrantfile
  - vendor

# Search index settings
search:
  host: localhost:9200
  index:
    name: epages-docs
    settings:
      mappings:
        page:
          properties:
            url:
              type: string
              analyzer: keyword
            title:
              type: string
              analyzer: english
            content:
              type: string
              analyzer: english
        section:
          properties:
            url:
              type: string
              analyzer: keyword
            title:
              type: string
              analyzer: english
            content:
              type: string
              analyzer: english
