# Site settings
email: documentation@epages.com
app_scopes: ["customers_read", "customers_write", "legal_read", "legal_write", "newsletters_read", "orders_read", "orders_write", "products_read", "products_write", "products_read_batch"]
url: "https://developer.epages.com"
baseurl: ""
github_url: "https://github.com/ePages-de/epages-docs"
google_analytics:
  default:
    id: UA-71308214-1
  blog:
    id: UA-71308214-2
  devjobs:
    id: UA-71308214-3

future: true
permalink: /blog/:year/:month/:day/:title.html
paginate: 5
paginate_path: "/blog/page-:num/"
raml:
  - key_prefix: "apps-api-"
    url_prefix: "apps/api-reference/"
    root_file: "_raml/apps/api.raml"
    api_versions: "_raml/**/*/api.raml"

# Build settings
markdown: kramdown
exclude:
  - circle.yml
  - docker-compose.yml
  - Dockerfile.nginx
  - Dockerfile.ruby
  - Gemfile
  - Gemfile.lock
  - LICENSE-CC-BY-40.txt
  - LICENSE-MIT.txt
  - Rakefile
  - README.md
  - vendor
  - apps/v-6.
  - apps/v-7.
include:
  - videos
gem:
  - jekyll-include-cache
